# Dive into Deep Learning (DDL): Ch. 2.1,2.2
Kushagra Ghosh, DDL: https://d2l.ai/

In [1]:
#Store data using n dimensional arrays called tensors
#Similar to ndarray in NumPy but it leverages GPUs to accelerate numberic computation, and it supports automatic differentiation)

#import PyTorch library
import torch

In [2]:
#1d tensor is vector, 2 axes called a matrix, more is called kth order tensor

#arange(n) used to create a vector of evenly spaced values (12 elements), starting at 0 (included) and ending at n (not included). Stored in main mem and designated for CPU-based computation.
x = torch.arange(12, dtype=torch.float32)
print(x)

print(x.numel()) #num elements in the tensor
print(x.shape) #tensor’s shape (the length along each axis)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])
12
torch.Size([12])


In [3]:
# reshape to change shape of tensor without changing vals. From (12,) -> (3,4)
X = x.reshape(3, 4)
print(X)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


In [4]:
print(torch.zeros((2, 3, 4))) #tensor with all zeroes
print(torch.ones((2, 3, 4))) #tensor with all ones

torch.randn(3, 4) #random elements drawn from Guassian (normal) distribution w/ mean 0 and stdev 1
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]]) #making tensor with exact vals for each element (outer list axis 0, inner list axis 1)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [5]:
print(X[-1], X[1:3]) #slicing
X[1, 2] = 17 #writing
X[:2, :] = 12 #assigning multiple elements the same val
print(X)

tensor([ 8.,  9., 10., 11.]) tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])


In [6]:
#elementwise operation (scalar operation to each element of tensor, scalar -> scalar), unary (taking 1 input) and goes from real num to real num
print(torch.exp(x)) #e^x

#binary scalar operation, pair of real num -> single val nun, lifting scalar func to elementwise vector/tensor operation
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
print(x + y, x - y, x * y, x / y, x ** y)

tensor([162754.7969, 162754.7969, 162754.7969, 162754.7969, 162754.7969,
        162754.7969, 162754.7969, 162754.7969,   2980.9580,   8103.0840,
         22026.4648,  59874.1406])
tensor([ 3.,  4.,  6., 10.]) tensor([-1.,  0.,  2.,  6.]) tensor([ 2.,  4.,  8., 16.]) tensor([0.5000, 1.0000, 2.0000, 4.0000]) tensor([ 1.,  4., 16., 64.])


In [7]:
#concatenate tensors (stacking them)
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

print(torch.cat((X, Y), dim=0)) #stacking them along rows (axis 0, new axis 0 len is 3+3)
print(torch.cat((X, Y), dim=1)) #stacking them along rows (axis 1, new axis 1 len is 4+4)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])
tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])


In [8]:
#binary tensor with logical statements
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [9]:
#summing all elem of tensor gives tensor w/ 1 element
X.sum()

tensor(66.)

In [10]:
#broadcasting: expand array by copying element along axes w/ length 1 to make both tensors have same shape, then do elementwise operation
a = torch.arange(3).reshape(3, 1)
b = torch.arange(2).reshape(1, 2)
print(a, b)
a+b #replicating a along cols and b along rows

tensor([[0],
        [1],
        [2]]) tensor([[0, 1]])


tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [11]:
#Python first evaluates Y + X, allocating new mem for result, then points Y to this new location in mem (dereferneces tensor that Y used to point to and point Y at new allocated mem)
before = id(Y)
Y = Y+X
id(Y) == before

False

In [12]:
#We want in-place updates since we may point at same parameters from multiple variables, and we want to update all of those references to avoid memory leak or refering to stale parameters

Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y #in-place operation
print('id(Z):', id(Z))

before = id(Y)
Y += X #same as Y[:] = Y + X, in-place
id(Y) == before

id(Z): 140264904398704
id(Z): 140264904398704


True

In [13]:
A = X.numpy() #Torch tensor -> NumPy array
B = torch.from_numpy(A) #NumPy array -> Torch tensor
type(A), type(B)

a = torch.tensor([3.5])
a, a.item(), float(a), int(a) #Size 1 tensor -> scalar

(tensor([3.5000]), 3.5, 3.5, 3)

In [14]:
#Reading CSV files and loading datasets into pandas

import os

os.makedirs(os.path.join('..', 'content', 'data'), exist_ok=True)
data_file = os.path.join('..', 'content', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('''NumRooms,RoofType,Price
NA,NA,127500
2,NA,106000
4,Slate,178100
NA,NA,140000''')

import pandas as pd

data = pd.read_csv(data_file)
print(data)

inputs, targets = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = pd.get_dummies(inputs, dummy_na=True) #Treating NaN and Slate as two differen categories of RoofType for 2 seperate columns
inputs = inputs.fillna(inputs.mean()) #Replacing NaN values for NumRooms with mean of column
print(inputs)

X = torch.tensor(inputs.to_numpy(dtype=float))
y = torch.tensor(targets.to_numpy(dtype=float))
X, y #Load into tensor

   NumRooms RoofType   Price
0       NaN      NaN  127500
1       2.0      NaN  106000
2       4.0    Slate  178100
3       NaN      NaN  140000
   NumRooms  RoofType_Slate  RoofType_nan
0       3.0           False          True
1       2.0           False          True
2       4.0            True         False
3       3.0           False          True


(tensor([[3., 0., 1.],
         [2., 0., 1.],
         [4., 1., 0.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))